### ISSUE TITLE
Search engine friendly URL

### ISSUE THREAD

**Issue by manishtiwari25** [linkdotnet/Blog#202]
hey, 
Instead of id for the blog post URL can we use title? replace spaces with - (Hyphen)? 
Or all writer to create a URL.

**Comment by linkdotnet** [comment]
Hey @manishtiwari25,

I fiddled around with the idea of using something other than this ugly `Guid`. And it boils down to finding a format that is somewhat bidirectional so that we can identify the blog post from the URL uniquely. 
Also, it should "survive" a title change (or any sort of change that might fiddle with the URL). Once you distributed a link it should be stable and should always point to the correct blog post.

I am really open for ideas here. I like to tackle this as the current approach is not really nice.

**Comment by diegodrf** [comment]
I don't know too much about the SEO rules, but I think it could help.

I saw a website that uses the title in the URL and I paid attention to understanding it.

Follow an example `https://g1.globo.com/economia/noticia/2023/06/29/entenda-como-a-contagem-da-populacao-pelo-ibge-influencia-o-orcamento-das-cidades.ghtml`

It's a Brazilian news website. Bellow I will split the URL to describe each part.

`https://g1.globo.com/` - It's the host part.

`economia/noticia/` - It's the group or section of the news.

`2023/06/29/` - It's the date posted.

`entenda-como-a-contagem-da-populacao-pelo-ibge-influencia-o-orcamento-das-cidades.ghtml` - It's the news title.

I paid attention at this section `2023/06/29/entenda-como-a-contagem-da-populacao-pelo-ibge-influencia-o-orcamento-das-cidades.ghtml` . Inserting the publish date avoids part of the conflicts in the URL because the query could search for publish date + title and the published data in this URL is friendly for the user.

**Comment by linkdotnet** [comment]
@diegodrf Any help here is welcome. I also tried this issue some time back and I just share my experience and my walls I did hit.

I started to have a "Slug" that is generated when the blog post is created. As you said, that could be a combination of title and date.

Here is the tricky part. The current workflow is like this:
1. The ShortBlogPost component currently only holds the `Id` as part of the URL. Here we have to support **both** approaches. Basically if someone like me already has indexed URLs with the `Guid` this should still work. So basically both URLs should work.
2. In the ShowBlogPostPage also both formats have to be supported and inside `OnParameterSetAsync` has to handle this. If there is a slug, use this otherwise use the ID.

The direct consequence is that you have to extend the Repository as this only allows retrieval via `GetById` - that is obviously not enough for the Slug.

Also you have to check (when creating the Slug), if the Slug already exists in the Repository.

**Comment by linkdotnet** [comment]
Thanks for looking into this @manishtiwari25 
I really would like to look into this further. As you already tried a few things - what was the showstopper for you?

**Comment by Kamyab7** [comment]
@linkdotnet As I know the best solution to reach this goal is passing both GUID and a SEO-friendly title in the URL at the same time.
 GUID is used to retrieve the correct blog post and title used to improve SEO.
I would like to help with this issue.

**Comment by linkdotnet** [comment]
Hey @Kamyab7 - a helping hand is always welcome!
I tried to support both to ensure backwards compatibility. In theory you can check if the given parameter is GUID-parsable, if not it has to be the Slug.

If you need some assistance, let me know.

**Comment by Kamyab7** [comment]
@linkdotnet Good idea! 
Let me try my first shot I will tell you if I need help.
