### ISSUE TITLE
Feature Request: Add Featured Image to Blog Posts

### ISSUE THREAD

**Issue by Esmaeli** [linkdotnet/Blog#321]
Hello, 
I noticed that there's no functionality for adding a featured image to blog posts. This would be a useful feature for posts and readers.

**Comment by linkdotnet** [comment]
Hey @Esmaeli,

Thanks for asking. Well, I am not sure if I fully understand your request.
In the current state, you can provide two images: A preview image and a fallback preview image.

They are not only used for the blog post itself but also for social media posts (OG Data tags) and also for RSS Feed Reader. 

The difference between the non-fallback and fallback is that it is a priority between them.
The normal way is to have a modern image format like webp/avif as "preview" image and "jpeg" as fallback. For example LinkedIn can't cope with avif/webp images, therefore you have to provide a jpg/png image as fallback.

**Comment by Esmaeli** [comment]
Hi @linkdotnet 
Thank you for the answer, but in the preview that you published on GitHub as a GIF file, when publishing the post, I did not see a place to select the image as the preview image or the fallback preview image, and for this reason, I sent this request, and when I checked your personal blog and I was surprised to see that there is a preview image.

If we only need to add a photo inside the post itself so that it can be shared on social networks, maybe it is better to include an option to attach a preview image and consider it specifically.

**Comment by linkdotnet** [comment]
Yeah, that preview is roughly 2 years old - I really have to adapt and renew it. You might see a "Preview Url" in the GIF as well - that is used for all that stuff.

Here a newer "picture":

<img width="769" alt="image" src="https://github.com/linkdotnet/Blog/assets/26365461/949d5257-6f4f-4b83-a36a-c62677f79f16">

Currently, you have to provide the URL to the image itself - there is no way of uploading because that would mean you need something like an Azure Blog Storage or so. And I did not build this abstraction until now.
